# Generated by Django 4.2.7 on 2023-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField()),
                ('no_of_people', models.IntegerField(choices=[(1, 'People 1'), (2, 'People 2'), (3, 'People 3')])),
                ('special_request', models.TextField()),
            ],
        ),
    ]
