# Generated by Django 4.2.7 on 2023-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_people',
            field=models.IntegerField(choices=[(1, 'People 1'), (2, 'People 2'), (3, 'People 3'), (4, 'People 4')]),
        ),
    ]
